name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repositoryni olish
        uses: actions/checkout@v4

      - name: Python o‘rnatish
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kutubxonalarni o‘rnatish
        run: |
          pip install -r requirements.txt

      - name: Python syntax tekshirish
        run: |
          python -m compileall app

      - name: Renderga deploy yuborish
        run: |
          curl "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
